name: newsly
description: Daily News in your hands

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 5.0.0+5

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  webfeed: ^0.7.0
  provider: ^6.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.18
  shared_preferences: ^2.0.13
  restart_app: ^1.1.0
  flutter_email_sender: ^5.1.0
  image_picker: ^0.8.4+8
  flutter_staggered_animations: ^1.0.0
  weather: ^2.0.1
  geolocator: ^8.1.1
  flutter_svg: ^1.0.3
  country_picker: ^2.0.11
  flutter_local_notifications: ^9.3.2
  notification_permissions: ^0.6.1
  workmanager: ^0.4.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.5
  introduction_screen: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  background_image: "assets/background.png"
  fullscreen: true
  image: assets/splash_image.png
  android_gravity: center
  
dependency_overrides:
  shared_preferences_android: 2.0.10 

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # categories assets
    - assets/categories/business.jpg
    - assets/categories/entertainment.jpg
    - assets/categories/general.jpg
    - assets/categories/health.jpg
    - assets/categories/science.jpg
    - assets/categories/sports.jpg
    - assets/categories/technology.jpg
    - assets/categories/arab_world.jpg
    # business news assets
    - assets/news_providers/business/alarabia.jpg
    - assets/news_providers/business/bbc_arabic.jpg
    - assets/news_providers/business/bbc_news_business.jpg
    - assets/news_providers/business/cnn_money.png
    - assets/news_providers/business/financial_times.jpg
    # entertainment news assets
    - assets/news_providers/entertainment/elle_fashion.jpg
    - assets/news_providers/entertainment/bbc_entertainment.jpg
    # world news assets
    - assets/news_providers/world/bbc_news.jpg
    - assets/news_providers/world/cnbc.jpg
    - assets/news_providers/world/cnn.jpg
    - assets/news_providers/world/dw.jpg
    - assets/news_providers/world/france24.jpg
    - assets/news_providers/world/new_york_times.jpg
    - assets/news_providers/world/reddit.jpg
    - assets/news_providers/world/rt.jpg
    - assets/news_providers/world/sky_news.png
    - assets/news_providers/world/the_guardian.jpg
    - assets/news_providers/world/the_wall_street_journal.jpg
    - assets/news_providers/world/the_washington_post.jpg
    - assets/news_providers/world/awsat.png
    # health news assets
    - assets/news_providers/health/covid_19.jpg
    - assets/news_providers/health/who.jpeg
    - assets/news_providers/health/united_nations.jpg
    # science news assets
    - assets/news_providers/science/new_york_times.jpg
    - assets/news_providers/science/forbes_science.jpg
    - assets/news_providers/science/huffpost.jpg
    - assets/news_providers/science/bbc_arabic.jpg
    # sports news assets
    - assets/news_providers/sports/almalaeb.jpg
    - assets/news_providers/sports/arabs-sport.png
    - assets/news_providers/sports/bbc_sport.jpg
    - assets/news_providers/sports/cnn_sport.jpg
    - assets/news_providers/sports/espn.jpg
    - assets/news_providers/sports/fifa.jpg
    - assets/news_providers/sports/fox_sports.png
    # technology news assets
    - assets/news_providers/technology/the_verg.png
    - assets/news_providers/technology/dw.jpg
    - assets/news_providers/technology/mit_tech.png
    # arab world news assets
    - assets/news_providers/arab_world/alarab_today.png
    - assets/news_providers/arab_world/alarabia.jpg
    - assets/news_providers/arab_world/aljazeera_arabic.jpg
    - assets/news_providers/arab_world/ammon.jpg
    - assets/news_providers/arab_world/bbc_arabic.jpg
    - assets/news_providers/arab_world/cnn_arabic.jpg
    - assets/news_providers/arab_world/dw_arabic.jpg
    - assets/news_providers/arab_world/france24_arabic.jpg
    - assets/news_providers/arab_world/rt_arabic.jpg
    - assets/news_providers/arab_world/sabaq.jpg
    - assets/news_providers/arab_world/spa.png
    - assets/news_providers/arab_world/awsat.png
    - assets/developer.png
    - assets/logos/paypal_logo.png
    - assets/logos/instagram_logo.png
    - assets/logos/twitter_logo.png
    - assets/logos/facebook_logo.png
    - assets/logos/world_health_organization.png
    # subCategories
    - assets/sub_categories/weather.jpg
    - assets/sub_categories/covid19.jpg
    # weather Icons
    - assets/weather/cloud.svg
    - assets/weather/cloudy.svg
    - assets/weather/drizzle.svg
    - assets/weather/fog.svg
    - assets/weather/rain.svg
    - assets/weather/snow.svg
    - assets/weather/thunderstorm.svg
    - assets/weather/clear.svg
    # covid 19 symptoms
    - assets/covid_symptoms/body_aches.png
    - assets/covid_symptoms/chills.png
    - assets/covid_symptoms/cough.png
    - assets/covid_symptoms/diarrhea.png
    - assets/covid_symptoms/fatigue.png
    - assets/covid_symptoms/fever.png
    - assets/covid_symptoms/headache.png
    - assets/covid_symptoms/loss_taste_smell.png
    - assets/covid_symptoms/nausea.png
    - assets/covid_symptoms/runny_nose.png
    - assets/covid_symptoms/shortness_breath.png
    - assets/covid_symptoms/sore_throat.png
    # covid 19 to be safe
    - assets/covid_be_safe/social_distance.png
    - assets/covid_be_safe/washing_hands.png
    - assets/covid_be_safe/wearing_mask.png
    # on boarding screens assets
    - assets/on_boarding/img1.png
    - assets/on_boarding/home.png
    - assets/on_boarding/covid.png
    - assets/on_boarding/weather.png
    - assets/on_boarding/articles.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MeaCulpa
      fonts:
        - asset: assets/fonts/meaculpa-regular.ttf
    - family: WeatherIcons
      fonts:
        - asset: assets/fonts/weathericons-regular.ttf
    - family: GideonRoman
      fonts:
        - asset: assets/fonts/gideonRoman_regular.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
